name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x # SDK Version to use.
        source-url: https://nuget.pkg.github.com/<owner>/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}  
        
    - run: dotnet build --configuration Release Paytrim.ValidationHelper
    - name: Create the package
      run: dotnet pack --configuration Release Paytrim.ValidationHelper
    - name: Publish the package to GPR
      run: dotnet nuget push Paytrim.ValidationHelper/bin/Release/*.nupkg
    
    - uses: actions/setup-dotnet@v1
    - name: Publish the package to nuget.org
      run: dotnet nuget push */bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
