name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Create the package
      run: dotnet pack --configuration Release Paytrim.ValidationHelper
    - name: Store artifact
      uses: actions/upload-artifact@v4
      with:
        name: nuget-package
        path: Paytrim.ValidationHelper/bin/Release/*.nupkg
        retention-days: 5
